language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gakinchi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  environment: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-123456789012"
  bucket_app: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_VARIABLE
  secret_access_key:
    secure: "$AWS_SECRETE_KEY_VARIABLE"